language: c

os:
    - linux

install:
    - mkdir -p build
    - cd build
    - wget -q http://embedthis.com/software/makeme-0.10.4-src.tgz -O makeme.tgz
    - tar xvfz makeme.tgz
    - cd makeme-*
    - make boot
    - sudo make install
    - cd ../..

script:
    - ./configure
    - me -s
    - TRAVIS=1 me -s -v test

env:
  global:
   - secure: "hZ5tREh4u0tuLv184W7TVsIiKFq/C3EQTM8NIofqp90T6bxxM/8D0eujfoChioijd0t3iIN7vtzdXC49zLF7LVyglkoU97dv2rZubwlKAzIIzJ6mr/45kDC8TWKiAUe2hxjSHRgfeuPDFZghxitwcRGKeGBeYcR5gSurr3Tt1R/dDrOAvfU/Et/GM8G8+FZTZE3XjzAaUlHqk8VyNnSmfvvFMmf47m7QQSq+FbZmfQOLW6eFa2JC8eoiw2JX776IFntCrIxhzphEwhPHG7+07CA5X4i2teNtnTRg1oKHEt5yAr0sUHbyFnUTwn/RgzABxr4zF3B36Dpn0gIY+t88s19/HUHiMl+KlwjgmH5KXqN0zbzAekIwXZ/dTQcOBZV2tI40jN7urmR+nbucdb+nUuMZGmFssBIb9ZuN5JSC8P7att7QpGWYN3iQRMaV33rVLMajc6T1re37KsR23oKcsNVnIdlXu9NtZL2O0zUFZgY86DbOyxggETLSV79837IvIW0fUM0exNVLFFRYznbfzX9mu3ko6ULoXHH5tCG+V9nbxDaRxW9M6722M+QLvweRshDjmdvxQhgb9T0bxbzEl9tsBpIKA3avW/OVsBrIyE4bpRLtUs6/cj6HQOQev5YoS0FlW5Y6cgbIGfzrGm/e3r+xlAS84uRmrAT69sot9Iw="

addons:
  coverity_scan:
    project:
      name: "embedthis/appweb"
      description: "Build submitted via Travis CI"
    notification_email: dev@embedthis.com
    build_command_prepend: "./configure; make clean"
    build_command: "type me ; make -j 1"
    branch_pattern: "dev"
